### ISSUE TITLE
Making verifiability optional

### ISSUE THREAD

**Issue by alxdavids** [chris-wood/draft-sullivan-cfrg-oprf#15]
@chris-wood I spoke to Hugo Krawczyk at RWC and he mentioned being more general in this draft so that we cover OPRFs as well as VOPRFs (i.e. make verifiability optional). This would allow us to cover additional use-cases such as that of OPAQUE (https://eprint.iacr.org/2018/163.pdf) and SPHINCS (https://eprint.iacr.org/2018/695.pdf). It may also help to differentiate the techniques that we use from VRFs without obliviousness.

What do you think? I would be happy to write up the necessary changes.

**Comment by grittygrease** [comment]
I'm on board.

**Comment by chris-wood** [comment]
👍 sounds great!

**Comment by chris-wood** [comment]
@alxdavids do you think you'll be able to do this before Prague?

**Comment by alxdavids** [comment]
Yeah I think it would be good to get the changes in before then, so I'm happy to aim for that.

**Comment by alxdavids** [comment]
DOne
