### ISSUE TITLE
Expand test vectors with DLEQ proof outputs

### ISSUE THREAD

**Issue by chris-wood** [chris-wood/draft-sullivan-cfrg-oprf#6]

**Comment by alxdavids** [comment]
@chris-wood I was planning to add the DLEQ test vectors as part of the work that I am doing and I was wondering how exactly SHA-512 is used for curves P-384 and P-256 (and likewise SHA-256 for P-384 and P-512)? If I'm not mistaken, if you just take the hash output mod p then this will be biased, or am I missing something?

Also do you happen to have the code that you used to generate these?

**Comment by chris-wood** [comment]
Yeah, I'll add you to the repository.

**Comment by alxdavids** [comment]
Think this is done now so I am going to close it.

**Comment by chris-wood** [comment]
Works for me!
